/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data standards for the environmental review process conducted under the National Environmental Policy Act (NEPA). This standard provides a framework to ensure that all environmental, social, and economic data collected, used, and submitted during NEPA reviews adhere to consistent definitions, formats, and protocols.
 */
export interface NEPADataStandard {
  projects?: Project[] | null;
  /**
   * Collection of NEPA processes
   */
  processe_instances?: ProcessInstance[];
  /**
   * Collection of NEPA documents
   */
  documents?: Document[];
  /**
   * Collection of public comments
   */
  comments?: Comment[];
  /**
   * Collection of public engagement events
   */
  engagements?: Engagement[];
  /**
   * Collection of case events
   */
  case_events?: CaseEvent[];
  /**
   * Collection of GIS data
   */
  gis_data?: (
    | GisData
    | {
        [k: string]: unknown;
      }
  )[];
  /**
   * Collection of GIS data elements
   */
  gis_data_elements?: GisDataElement[];
  /**
   * Collection of user roles
   */
  user_roles?: UserRole[];
  /**
   * Collection of decision elements
   */
  decision_elements?: DecisionElement[];
  /**
   * Collection of process models
   */
  process_models?: ProcessModel[];
  /**
   * Collection of decision payloads
   */
  process_decision_payloads?: ProcessDecisionPayload[];
  /**
   * Collection of legal structures
   */
  legal_structures?: LegalStructure[];
  [k: string]: unknown;
}
/**
 * Represents the activity or decision requiring a NEPA review process. A project generally has a relationship with a GIS object defining its location, which establishes the physical footprint of the action.
 */
export interface Project {
  /**
   * database id
   */
  id: number;
  /**
   * Federal agency that supervises preparation of the environmental documents for the project.
   */
  lead_agency?: string;
  /**
   * Other involved agencies.
   */
  participating_agencies?: string;
  /**
   * Geographic area including GIS data
   */
  location_object?: {
    /**
     * Text description of the project location
     */
    description: string;
    /**
     * Reference to associated GIS data
     */
    gis_reference?: string;
    [k: string]: unknown;
  };
  /**
   * Environmental review initiation date (aggregated from process status)
   */
  start_date?: string;
  /**
   * Current phase (pre-application, underway, paused, completed) of the NEPA, permitting, or other authorization process (aggregated from process status).
   */
  current_status?: "pre-application" | "underway" | "paused" | "completed";
  /**
   * Center/centroid of project (shortcut for plotting on a map - should attach GIS data object as well)
   */
  location_lat?: number;
  /**
   * Center/centroid of project (shortcut for plotting on a map - should attach GIS data object as well)
   */
  location_lon?: number;
  /**
   * Name of responsible entity, organization, or person (contact information json object)
   */
  sponsor_contact?: {
    [k: string]: unknown;
  };
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  /**
   * created
   */
  created_at?: string;
  /**
   * Descriptive name of the project.
   */
  title: string;
  /**
   * Summary of the project’s goals and scope.
   */
  description: string;
  /**
   * High-level project category (e.g., energy, transportation, land management).
   */
  sector?: string;
  /**
   * Classification, a sub-type of sector (pipeline, highway, habitat restoration).
   */
  type?: string;
  /**
   * Link to federal, state, local or other funding by reference (e.g., grant program, loan guarantee, appropriated funds)
   */
  funding?: string;
  /**
   * Name of responsible entity, organization, or person.
   */
  sponsor: string;
  /**
   * If nesting projects, reference to the parent project's ID.
   */
  parent_project_id?: number;
  /**
   * Text field to specify location, eg. address or Well Known Text, WKT
   */
  location_text?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * The specific type of environmental review, permit, or authorization. cA process is associated with or nested beneath a project and will have documents associated and nested beneath it.
 */
export interface ProcessInstance {
  /**
   * Database primary key identifier
   */
  id: number;
  /**
   * created
   */
  created_at?: string;
  /**
   * Reference to Process ID of parent process, if applicable
   */
  parent_process_id?: number;
  /**
   * Reference to Project ID of parent process
   */
  parent_project_id: number;
  /**
   * Process-specific ID assigned by agency, if assigned
   */
  agency_id?: string;
  /**
   * Unique identification number assigned at federal level
   */
  federal_id?: string;
  /**
   * Level of NEPA review or other permit or authorization (see Permitting Council Federal Environmental Review and Authorization Inventory)
   */
  type: string;
  /**
   * Current status of the process
   */
  status: ("planned" | "underway" | "paused" | "completed") | string;
  /**
   * Current state of process, may be derived from the last case event with this Process ID
   */
  stage?: string;
  /**
   * Initiation date of the process
   */
  start_date?: string;
  /**
   * Conclusion date of the process
   */
  complete_date?: string;
  /**
   * Result (e.g., Record of Decision, permit issuance)
   */
  outcome?: string;
  /**
   * Federal agency that supervises preparation of the environmental documents for the project
   */
  lead_agency: string;
  /**
   * Joint lead agency, if applicable
   */
  joint_lead_agency?: string;
  /**
   * Cooperating agencies involved in the process
   */
  cooperating_agencies?: string[];
  /**
   * Other agencies involved in the process
   */
  participating_agencies?: string[];
  /**
   * Start date and time of public comment period
   */
  comment_start?: string;
  /**
   * End date and time of public comment period
   */
  comment_end?: string;
  /**
   * Purpose and need statement for the project
   */
  purpose_need?: string;
  /**
   * Miscellaneous notes on process instance model
   */
  notes?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * Detailed description of the process
   */
  description?: string;
  /**
   * Reference to the process model used for this process instance
   */
  process_model?: string | null;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  /**
   * Short internal process code used for mapping process types to external or legacy systems.
   */
  process_code?: string;
  [k: string]: unknown;
}
/**
 * Official records created during the NEPA review. The document object includes both metadata identifying the document and its context and a container for summary information that lays out, at a minimum, the table of contents of the document. Documents are also likely to have many GIS objects associated with them.
 */
export interface Document {
  /**
   * database id
   */
  id: number;
  /**
   * Document category, such as EIS, EA, etc.
   */
  document_type: string;
  /**
   * Document title.
   */
  title: string;
  /**
   * Volume title (e.g., Appendix)
   */
  volume_title?: string;
  /**
   * Publication or submission date.
   */
  publish_date?: string;
  /**
   * Responsible entity.
   */
  prepared_by: string;
  /**
   * Document production phase.
   */
  status?: string;
  /**
   * Online link if available.
   */
  url?: string;
  /**
   * Miscellaneous notes.
   */
  notes?: string;
  /**
   * Unique identification number for related document (if applicable)
   */
  related_document_id?: number;
  /**
   * container for summary information
   */
  document_summary?: {
    [k: string]: unknown;
  };
  /**
   * the table of contents (or heading structure) of the document.
   */
  document_toc?: {
    [k: string]: unknown;
  };
  /**
   * Public or restricted.
   */
  public_access?: boolean;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  /**
   * This jsonb field should contain any document files if applicable; this is an optional way of storing or transmitting files and is not necessary as this is primarily a data record for metadata about the document rather than the document itself.
   */
  document_files?: {
    [k: string]: unknown;
  };
  /**
   * creation date
   */
  created_at?: string;
  /**
   * Reference to Process ID of parent process for the document
   */
  parent_process_id: number;
  /**
   * Indicates which revision of the document (e.g., first revised Draft EIS) - numeric form
   */
  revision_number?: number;
  /**
   * Indicates which revision of the document (e.g., first revised Draft EIS) - numeric form
   */
  document_revision?: number;
  /**
   * Indicates supplement number
   */
  supplement_number?: number;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Feedback submitted by individuals or organizations during the NEPA process
 */
export interface Comment {
  /**
   * Database primary key identifier
   */
  id: number;
  /**
   * Name of individual or organization submitting the comment
   */
  commenter_entity: string;
  /**
   * Text of the comment
   */
  content_text: string;
  /**
   * Date the comment was submitted
   */
  date_submitted: string;
  /**
   * Reference to Document ID of the document to which the comment is related
   */
  parent_document_id: number;
  /**
   * Method used to submit the comment
   */
  submission_method?: string;
  /**
   * Formal reply from the agency, if applicable
   */
  response_text?: string;
  /**
   * Public source (database field)
   */
  public_source?: boolean;
  /**
   * Content as JSON (database field)
   */
  content_json?: {
    [k: string]: unknown;
  };
  /**
   * Response as JSON (database field)
   */
  response_json?: {
    [k: string]: unknown;
  };
  /**
   * Public access level for the comment (boolean)
   */
  public_access?: boolean;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Opportunities for interaction in the NEPA process, including formal consultation
 */
export interface Engagement {
  /**
   * Database primary key identifier
   */
  id: number;
  /**
   * Type of public engagement event
   */
  type: string;
  /**
   * Engagement start date/time
   */
  start_datetime: string;
  /**
   * Engagement end date/time
   */
  end_datetime?: string;
  /**
   * Physical, virtual, hybrid. (Note that this may also be attached as a relationship with a GIS object).
   */
  location?: string;
  /**
   * Reference to Process ID of the associated NEPA process(es) for this event
   */
  parent_process_id: number;
  /**
   * Number of participants at the event
   */
  attendance?: number;
  /**
   * Related document ID (database field)
   */
  related_document_id?: number;
  /**
   * Container for participation data.
   */
  participation?: {
    [k: string]: unknown;
  };
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * additional notes.
   */
  notes?: string;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Milestones or steps within the NEPA review, tracked in a case management system or other system, such as task management tools or reporting dashboards
 */
export interface CaseEvent {
  /**
   * database id
   */
  id: number;
  /**
   * Link to information about the event.
   */
  source?: string;
  /**
   * Event class (e.g., NOI, ROD)
   */
  type: string;
  /**
   * Optional event hierarchy (e.g., Tier 1 NOI, Tier 2 Scoping Complete, Tier 3 Task assigned to Jane Doe).
   */
  tier?: number;
  /**
   * Pending, completed, in progress.
   */
  status?: "pending" | "completed" | "in progress";
  /**
   * Result or action taken.
   */
  outcome?: string;
  /**
   *  Reference to Document ID of the document related to the event. Optional.
   */
  related_document_id?: number;
  /**
   * Indicates whether events can be displayed publicly. (Binary Y/N)
   */
  public_access?: boolean;
  /**
   * Description of event.
   */
  description?: string;
  /**
   * Responsible individuals or agencies.
   */
  assigned_entity?: string;
  /**
   * Name of segment following this event (e.g. if this is "start of scoping" the next segment is "scoping").
   */
  following_segment_name?: string;
  /**
   * If applicable, the parent ID of the event.
   */
  parent_event_id?: number;
  /**
   * Related engagement event if applicable
   */
  related_engagement_id?: number;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  /**
   * created
   */
  created_at?: string;
  /**
   * Reference to Process ID of the associated NEPA process for this event.
   */
  parent_process_id: number;
  /**
   * Name of event
   */
  name: string;
  /**
   * Date and time of event
   */
  datetime: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Geospatial data and metadata associated with NEPA projects
 */
export interface GisData {
  /**
   * database id
   */
  id: number;
  /**
   * Organization or individual.
   */
  creator?: (string | null) & string;
  /**
   * Optional description
   */
  description?: (string | null) & string;
  /**
   * Optional.
   */
  extent?: (string | null) & string;
  /**
   * Miscellaneous notes.
   */
  notes?: (string | null) & string;
  /**
   * Inventory of map image container and GIS data container in json format (note inventory should be attached through gis_data_element objects, which may include a list of:
   * -	Format: GeoJSON, Shapefile, KML.
   * -	Access Method: URL, API, direct upload.
   * -	Coordinate System: Spatial reference system.
   * -	Bounding Box: Geographic extent.
   * -	Purpose: Bespoke, analysis, or base map.
   * -	Reference to database: Whether this object references an identified GIS analysis in an official inventory.
   */
  container_inventory?: {
    [k: string]: unknown;
  } | null;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_project_id?: (number | null) & number;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_process_id?: (number | null) & number;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_document_id?: (number | null) & number;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_case_event_id?: (number | null) & number;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_comment_id?: (number | null) & number;
  /**
   * Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
   */
  parent_engagement_id?: (number | null) & number;
  /**
   * created date
   */
  created_at?: string;
  /**
   * Option to specify single point or centroid for rapid plotting
   */
  centroid_lat?: number;
  /**
   * Option to specify single point or centroid for rapid plotting
   */
  centroid_lon?: number;
  /**
   * Contact card-type data for creator.
   */
  creator_contact?: {
    [k: string]: unknown;
  };
  /**
   * map image data
   */
  map_image?: {
    [k: string]: unknown;
  };
  /**
   * json container for any attached GIS data
   */
  data_container?: {
    [k: string]: unknown;
  };
  /**
   * address of centroid (if applicable)
   */
  address?: string;
  /**
   * Timestamp of last update to this dataset
   */
  last_updated?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Individual elements within GIS data containers with specific access and format information
 */
export interface GisDataElement {
  /**
   * database id
   */
  id?: number;
  /**
   * Reference to header or other information in GIS data container to locate this particular data element
   */
  container_reference?: string;
  /**
   * URL, API, direct upload.
   */
  access_method?: string;
  /**
   * Spatial reference system.
   */
  coordinate_system?: string;
  /**
   * Geographic extent.
   */
  top_left_lat?: number;
  /**
   * Geographic extent.
   */
  top_left_lon?: number;
  /**
   * Geographic extent.
   */
  bot_right_lat?: number;
  /**
   * Geographic extent.
   */
  bot_right_lon?: number;
  /**
   * 1.	Bespoke GIS Data: Project-specific (boundaries, analysis areas).
   * 2.	Analysis GIS Data: Data layers used for analysis (e.g., wetlands inventory).
   * 3.	Base Map Data: Foundational layers (streets, elevation).
   *
   */
  purpose?: "bespoke" | "analysis" | "base map";
  /**
   * Whether this object references an identified GIS analysis in an official inventory.
   */
  data_match?: string;
  /**
   * instructions for access to data
   */
  access_info?: {
    [k: string]: unknown;
  };
  /**
   * created date
   */
  created_at?: string;
  /**
   * Parent GIS data entity (accepts parent_gis or gis_id)
   */
  parent_gis?: number;
  /**
   * GeoJSON, Shapefile, KML. (accepts format or data_type)
   */
  format?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Defines stakeholders interacting with the NEPA IT system
 */
export interface UserRole {
  /**
   * database id
   */
  id: number;
  /**
   * Title of the role (Agency Staff, Public Commenter).
   */
  name: string;
  /**
   * Responsibilities and access rights.
   */
  description?: string;
  /**
   * role is a member of the broader class of public users/stakeholders
   */
  public?: boolean;
  /**
   * access policy json object
   */
  access_policy?: {
    [k: string]: unknown;
  };
  /**
   * System access levels description
   */
  permission_descriptions?: string;
  /**
   * created
   */
  created_at?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Individual criteria or conditions used in NEPA decision-making processes
 */
export interface DecisionElement {
  /**
   * database id
   */
  id: number;
  /**
   * A description of the type of thing being measured in the criteria (e.g. threshold of contamination)
   */
  measure?: string;
  /**
   * If the spatial relationship is a simple intersection (e.g. floodplain)
   */
  intersect?: boolean;
  /**
   *  A container for reference to the screening criteria (e.g. api call for wetland data)
   */
  spatial_reference?: {
    [k: string]: unknown;
  };
  /**
   * Text data to display on a screening form for a user to input data
   */
  form_text?: string;
  /**
   * A description of the type of response expected on the form (e.g. text, select from list, number)
   */
  form_response_desc?: string;
  /**
   * Formatted response for a formbuilder application (e.g. likert scale, number, etc)
   */
  form_data?: {
    [k: string]: unknown;
  };
  /**
   * A description of how the response is matched against the condition and what the results could be.
   */
  evaluation_method?: string;
  /**
   * Decision Model Notation description of evaluation of decision element.
   */
  evaluation_dmn?: {
    [k: string]: unknown;
  };
  /**
   * numeric value of the triggering measure (if applicable)
   */
  threshold?: number;
  /**
   * Whether the criterion is a spatial relationship
   */
  spatial?: boolean;
  /**
   * The category of the process decision element, such as limitation, condition, core, or extraordinary circumstances.
   */
  category?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  /**
   * This is a description of the expected data that will be used to evaluate the decision element, such as a list of possible responses or a schema for the data.
   */
  expected_evaluation_data?: {
    [k: string]: unknown;
  };
  /**
   * This jsonb field should contain the structure of data that will be returned by the logic engine - for example, if the response will be a json object containing a series of boolean yes/no indicators, this should specify the schema.
   */
  response_data?: {
    [k: string]: unknown;
  };
  /**
   * created
   */
  created_at?: string;
  /**
   * Parent process model
   */
  process_model: number;
  /**
   * If applicable, legal structure related to specific criteria
   */
  legal_structure_id?: number;
  /**
   * Name of element
   */
  title: string;
  /**
   * Plain language description of the criterion
   */
  description: string;
  /**
   * Process models may have complex decision trees - this string can reference the specific piece of the process model that this decision element applies to.
   */
  process_model_internal_reference_id?: string;
  /**
   * If this decision element depends on another decision element (e.g. if answer a is yes, ask question b), this field can be used to reference the parent decision element.
   */
  parent_decision_element_id?: number;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Template or framework for NEPA processes
 */
export interface ProcessModel {
  /**
   * database id
   */
  id: number;
  /**
   * Plain language description of the process model
   */
  description: string;
  /**
   * Object containing the BPMN representation of the process
   */
  bpmn_model?: {
    [k: string]: unknown;
  };
  /**
   * Reference to legal structure that defines the process (text, cfr reference, etc)
   */
  legal_structure_text?: string;
  /**
   * Plain language description of the screening criteria that would lead to starting the process for an individual project.
   */
  screening_description?: string;
  /**
   * Agency responsible for carrying out this process
   */
  agency?: string;
  /**
   * Decision model notation (in json wrapper) to structure logic for how to evaluate responses to decision elements. Optionally, each decision element may have individual DMN models.
   */
  DMN_model?: {
    [k: string]: unknown;
  };
  /**
   * Reference to parent model, if applicable (i.e. if this is a subprocess or flows from a previous process)
   */
  parent_model?: (string | null) & number;
  /**
   * created
   */
  created_at?: string;
  /**
   * Name of process model
   */
  title: string;
  /**
   * Miscellaneous notes on process model
   */
  notes?: string;
  /**
   * Reference to legal structure entity that defines the process
   */
  legal_structure_id?: number;
  /**
   * Plain language description of the screening criteria that would lead to starting the process for an individual project.  (json object option - this should not replace the decision element relationships)
   */
  screening_desc_json?: {
    [k: string]: unknown;
  };
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Data package containing decision-making information
 */
export interface ProcessDecisionPayload {
  /**
   * Database primary key identifier
   */
  id: number;
  /**
   * created
   */
  created_at?: string;
  /**
   * Reference to the associated process (accepts process field as integer)
   */
  process: number;
  /**
   * The actual decision data payload
   */
  evaluation_data?: {
    [k: string]: unknown;
  };
  /**
   * Description of the payload data
   */
  data_description?: string;
  /**
   * Response from the decision process
   */
  response?: string;
  /**
   * Result of the decision
   */
  result?: string;
  /**
   * Boolean result of the decision
   */
  result_bool?: boolean;
  /**
   * Notes about the decision result
   */
  result_notes?: string;
  /**
   * Data associated with the result
   */
  result_data?: {
    [k: string]: unknown;
  };
  /**
   * Source of the decision result
   */
  result_source?: string;
  /**
   * Annotations on the payload data
   */
  data_annotation?: string;
  /**
   * Annotations on the evaluation data
   */
  evaluation_data_annotation?: {
    [k: string]: unknown;
  };
  /**
   * Reference to the decision element this payload responds to
   */
  process_decision_element?: string | null;
  /**
   * Reference to the project this decision payload is associated with
   */
  project?: string | null;
  /**
   * Reference to parent payload ID (e.g., if this is a response to a submission)
   */
  parent_payload?: string | null;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
/**
 * Legal, policy, or process data guiding the NEPA process, including thresholds and conditions for level of reviews or other decision criteria
 */
export interface LegalStructure {
  /**
   * database id
   */
  id: number;
  /**
   * Official name.
   */
  title: string;
  /**
   * Legal reference.
   */
  citation: string;
  /**
   * Summary and relevance.
   */
  description?: string;
  /**
   * Government body.
   */
  issuing_authority?: string;
  /**
   * Implementation date.
   */
  effective_date?: string;
  /**
   * Full text or excerpt.
   */
  context?: string;
  /**
   * Procedural mandates, ideally structured as data using an ontology that includes facts (such as thresholds triggering processes), duties, and actors (e.g., FLINT frames).
   */
  compliance_data?: {
    [k: string]: unknown;
  };
  /**
   * URL of legal reference (e.g. eCFR)
   */
  url?: string;
  /**
   * created
   */
  created_at?: string;
  /**
   * This jsonb field should be used for additional data structures as needed.
   */
  other?: {
    [k: string]: unknown;
  };
  /**
   * This is the owner of the original data, generally the authoritative data source.
   */
  record_owner_agency?: string;
  /**
   * This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
   */
  data_source_agency?: string;
  /**
   * This is the system from which this data record was sent or retrieved or in which it is stored.
   */
  data_source_system?: string;
  /**
   * This is the version of this data record.
   */
  data_record_version?: string;
  /**
   * This is the last update of the data record in the system.
   */
  last_updated?: string;
  /**
   * This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
   */
  retrieved_timestamp?: string;
  [k: string]: unknown;
}
