# generated by datamodel-codegen:
#   filename:  nepa.schema.json
#   timestamp: 2026-04-06T20:10:34+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, conint


class LocationObject(BaseModel):
    """
    Geographic area including GIS data
    """

    description: str
    """
    Text description of the project location
    """
    gis_reference: Optional[str] = None
    """
    Reference to associated GIS data
    """


class CurrentStatus(Enum):
    """
    Current phase (pre-application, underway, paused, completed) of the NEPA, permitting, or other authorization process (aggregated from process status).
    """

    pre_application = 'pre-application'
    underway = 'underway'
    paused = 'paused'
    completed = 'completed'


class Project(BaseModel):
    """
    Represents the activity or decision requiring a NEPA review process. A project generally has a relationship with a GIS object defining its location, which establishes the physical footprint of the action.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    lead_agency: Optional[str] = None
    """
    Federal agency that supervises preparation of the environmental documents for the project.
    """
    participating_agencies: Optional[List[str]] = None
    """
    Other involved agencies.
    """
    location_object: Optional[LocationObject] = None
    """
    Geographic area including GIS data
    """
    start_date: Optional[date] = None
    """
    Environmental review initiation date (aggregated from process status)
    """
    current_status: Optional[CurrentStatus] = None
    """
    Current phase (pre-application, underway, paused, completed) of the NEPA, permitting, or other authorization process (aggregated from process status).
    """
    location_lat: Optional[float] = None
    """
    Center/centroid of project (shortcut for plotting on a map - should attach GIS data object as well)
    """
    location_lon: Optional[float] = None
    """
    Center/centroid of project (shortcut for plotting on a map - should attach GIS data object as well)
    """
    sponsor_contact: Optional[Dict[str, Any]] = None
    """
    Name of responsible entity, organization, or person (contact information json object)
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    last_updated: Optional[AwareDatetime] = None
    """
    This is the last update of the data record in the system.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    retrieved_timestamp: Optional[AwareDatetime] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """
    created_at: Optional[str] = None
    """
    created
    """
    title: str
    """
    Descriptive name of the project.
    """
    description: str
    """
    Summary of the project’s goals and scope.
    """
    sector: Optional[str] = None
    """
    High-level project category (e.g., energy, transportation, land management).
    """
    type: Optional[str] = None
    """
    Classification, a sub-type of sector (pipeline, highway, habitat restoration).
    """
    funding: Optional[str] = None
    """
    Link to federal, state, local or other funding by reference (e.g., grant program, loan guarantee, appropriated funds)
    """
    sponsor: str
    """
    Name of responsible entity, organization, or person.
    """
    parent_project_id: Optional[int] = None
    """
    If nesting projects, reference to the parent project's ID. 
    """
    location_text: Optional[str] = None
    """
    Text field to specify location, eg. address or Well Known Text, WKT
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """


class Status(Enum):
    """
    Indicates status of process
    """

    planned = 'planned'
    underway = 'underway'
    paused = 'paused'
    completed = 'completed'


class ProcessInstance(BaseModel):
    """
    The specific type of environmental review, permit, or authorization. cA process is associated with or nested beneath a project and will have documents associated and nested beneath it.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    Database primary key identifier
    """
    created_at: Optional[str] = None
    """
    created
    """
    parent_process_id: Optional[int] = None
    """
    Reference to Process ID of parent process, if applicable
    """
    parent_project_id: int
    """
    Reference to Project ID of parent process
    """
    agency_id: Optional[str] = None
    """
    Process-specific ID assigned by agency, if assigned
    """
    federal_id: Optional[str] = None
    """
    Unique identification number assigned at federal level
    """
    type: str
    """
    Level of NEPA review or other permit or authorization (see Permitting Council Federal Environmental Review and Authorization Inventory)
    """
    status: Union[Status, str]
    """
    Current status of the process
    """
    stage: Optional[str] = None
    """
    Current state of process, may be derived from the last case event with this Process ID
    """
    start_date: Optional[date] = None
    """
    Initiation date of the process
    """
    complete_date: Optional[date] = None
    """
    Conclusion date of the process
    """
    outcome: Optional[str] = None
    """
    Result (e.g., Record of Decision, permit issuance)
    """
    lead_agency: str
    """
    Federal agency that supervises preparation of the environmental documents for the project
    """
    joint_lead_agency: Optional[str] = None
    """
    Joint lead agency, if applicable
    """
    cooperating_agencies: Optional[List[str]] = None
    """
    Cooperating agencies involved in the process
    """
    participating_agencies: Optional[List[str]] = None
    """
    Other agencies involved in the process
    """
    comment_start: Optional[AwareDatetime] = None
    """
    Start date and time of public comment period
    """
    comment_end: Optional[AwareDatetime] = None
    """
    End date and time of public comment period
    """
    purpose_need: Optional[str] = None
    """
    Purpose and need statement for the project
    """
    notes: Optional[str] = None
    """
    Miscellaneous notes on process instance model
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed.
    """
    description: Optional[str] = None
    """
    Detailed description of the process
    """
    process_model: Optional[str] = None
    """
    Reference to the process model used for this process instance
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """
    process_code: Optional[str] = None
    """
    Short internal process code used for mapping process types to external or legacy systems.
    """


class Document(BaseModel):
    """
    Official records created during the NEPA review. The document object includes both metadata identifying the document and its context and a container for summary information that lays out, at a minimum, the table of contents of the document. Documents are also likely to have many GIS objects associated with them.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    document_type: str
    """
    Document category, such as EIS, EA, etc. 
    """
    title: str
    """
    Document title.
    """
    volume_title: Optional[str] = None
    """
    Volume title (e.g., Appendix)
    """
    publish_date: Optional[date] = None
    """
    Publication or submission date.
    """
    prepared_by: str
    """
    Responsible entity.
    """
    status: Optional[str] = None
    """
    Document production phase. 
    """
    url: Optional[AnyUrl] = None
    """
    Online link if available.
    """
    notes: Optional[str] = None
    """
    Miscellaneous notes.
    """
    related_document_id: Optional[int] = None
    """
    Unique identification number for related document (if applicable)
    """
    document_summary: Optional[Dict[str, Any]] = None
    """
    container for summary information
    """
    document_toc: Optional[Dict[str, Any]] = None
    """
    the table of contents (or heading structure) of the document.
    """
    public_access: Optional[bool] = None
    """
    Public or restricted.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    last_updated: Optional[AwareDatetime] = None
    """
    This is the last update of the data record in the system.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    retrieved_timestamp: Optional[AwareDatetime] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """
    document_files: Optional[Dict[str, Any]] = None
    """
    This jsonb field should contain any document files if applicable; this is an optional way of storing or transmitting files and is not necessary as this is primarily a data record for metadata about the document rather than the document itself. 
    """
    created_at: Optional[str] = None
    """
    creation date
    """
    parent_process_id: int
    """
    Reference to Process ID of parent process for the document
    """
    revision_number: Optional[int] = None
    """
    Indicates which revision of the document (e.g., first revised Draft EIS) - numeric form
    """
    document_revision: Optional[int] = None
    """
    Indicates which revision of the document (e.g., first revised Draft EIS) - numeric form
    """
    supplement_number: Optional[int] = None
    """
    Indicates supplement number
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """


class Comment(BaseModel):
    """
    Feedback submitted by individuals or organizations during the NEPA process
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    Database primary key identifier
    """
    commenter_entity: str
    """
    Name of individual or organization submitting the comment
    """
    content_text: str
    """
    Text of the comment
    """
    date_submitted: date
    """
    Date the comment was submitted
    """
    parent_document_id: int
    """
    Reference to Document ID of the document to which the comment is related
    """
    submission_method: Optional[str] = None
    """
    Method used to submit the comment
    """
    response_text: Optional[str] = None
    """
    Formal reply from the agency, if applicable
    """
    public_source: Optional[bool] = None
    """
    Public source (database field)
    """
    content_json: Optional[Dict[str, Any]] = None
    """
    Content as JSON (database field)
    """
    response_json: Optional[Dict[str, Any]] = None
    """
    Response as JSON (database field)
    """
    public_access: Optional[bool] = None
    """
    Public access level for the comment (boolean)
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class Engagement(BaseModel):
    """
    Opportunities for interaction in the NEPA process, including formal consultation
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    Database primary key identifier
    """
    type: str
    """
    Type of public engagement event
    """
    start_datetime: AwareDatetime
    """
    Engagement start date/time
    """
    end_datetime: Optional[AwareDatetime] = None
    """
    Engagement end date/time
    """
    location: Optional[str] = None
    """
    Physical, virtual, hybrid. (Note that this may also be attached as a relationship with a GIS object).
    """
    parent_process_id: int
    """
    Reference to Process ID of the associated NEPA process(es) for this event
    """
    attendance: Optional[conint(ge=0)] = None
    """
    Number of participants at the event
    """
    related_document_id: Optional[int] = None
    """
    Related document ID (database field)
    """
    participation: Optional[Dict[str, Any]] = None
    """
    Container for participation data.
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    notes: Optional[str] = None
    """
    additional notes.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class Status1(Enum):
    """
    Pending, completed, in progress.
    """

    pending = 'pending'
    completed = 'completed'
    in_progress = 'in progress'


class CaseEvent(BaseModel):
    """
    Milestones or steps within the NEPA review, tracked in a case management system or other system, such as task management tools or reporting dashboards
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    source: Optional[str] = None
    """
    Link to information about the event.
    """
    type: str
    """
    Event class (e.g., NOI, ROD)
    """
    tier: Optional[int] = None
    """
    Optional event hierarchy (e.g., Tier 1 NOI, Tier 2 Scoping Complete, Tier 3 Task assigned to Jane Doe). 
    """
    status: Optional[Status1] = None
    """
    Pending, completed, in progress.
    """
    outcome: Optional[str] = None
    """
    Result or action taken.
    """
    related_document_id: Optional[int] = None
    """
     Reference to Document ID of the document related to the event. Optional.
    """
    public_access: Optional[bool] = None
    """
    Indicates whether events can be displayed publicly. (Binary Y/N)
    """
    description: Optional[str] = None
    """
    Description of event. 
    """
    assigned_entity: Optional[str] = None
    """
    Responsible individuals or agencies.
    """
    following_segment_name: Optional[str] = None
    """
    Name of segment following this event (e.g. if this is "start of scoping" the next segment is "scoping").
    """
    parent_event_id: Optional[int] = None
    """
    If applicable, the parent ID of the event. 
    """
    related_engagement_id: Optional[int] = None
    """
    Related engagement event if applicable
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    last_updated: Optional[AwareDatetime] = None
    """
    This is the last update of the data record in the system.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    retrieved_timestamp: Optional[AwareDatetime] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """
    created_at: Optional[str] = None
    """
    created
    """
    parent_process_id: int
    """
    Reference to Process ID of the associated NEPA process for this event.
    """
    name: str
    """
    Name of event
    """
    datetime: str
    """
    Date and time of event
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """


class BoundingBox(BaseModel):
    """
    Geographic extent of the data
    """

    north: Optional[float] = None
    """
    Northern boundary coordinate
    """
    south: Optional[float] = None
    """
    Southern boundary coordinate
    """
    east: Optional[float] = None
    """
    Eastern boundary coordinate
    """
    west: Optional[float] = None
    """
    Western boundary coordinate
    """


class Purpose(Enum):
    """
    Purpose of the GIS data (project-specific, analysis, or foundational layers)
    """

    bespoke = 'bespoke'
    analysis = 'analysis'
    base_map = 'base map'


class ContainerInventory(BaseModel):
    """
    Inventory of map image container and GIS data container in json format (note inventory should be attached through gis_data_element objects, which may include a list of:
    -	Format: GeoJSON, Shapefile, KML.
    -	Access Method: URL, API, direct upload.
    -	Coordinate System: Spatial reference system.
    -	Bounding Box: Geographic extent.
    -	Purpose: Bespoke, analysis, or base map.
    -	Reference to database: Whether this object references an identified GIS analysis in an official inventory.
    """

    format: Optional[str] = None
    """
    Format of the GIS data
    """
    access_method: Optional[str] = None
    """
    Method to access the GIS data
    """
    coordinate_system: Optional[str] = None
    """
    Spatial reference system used
    """
    bounding_box: Optional[BoundingBox] = None
    """
    Geographic extent of the data
    """
    purpose: Optional[Purpose] = None
    """
    Purpose of the GIS data (project-specific, analysis, or foundational layers)
    """


class ContainerInventory1(BaseModel):
    """
    Inventory of map image container and GIS data container in json format (note inventory should be attached through gis_data_element objects, which may include a list of:
    -	Format: GeoJSON, Shapefile, KML.
    -	Access Method: URL, API, direct upload.
    -	Coordinate System: Spatial reference system.
    -	Bounding Box: Geographic extent.
    -	Purpose: Bespoke, analysis, or base map.
    -	Reference to database: Whether this object references an identified GIS analysis in an official inventory.
    """

    format: Optional[str] = None
    """
    Format of the GIS data
    """
    access_method: Optional[str] = None
    """
    Method to access the GIS data
    """
    coordinate_system: Optional[str] = None
    """
    Spatial reference system used
    """
    bounding_box: Optional[BoundingBox] = None
    """
    Geographic extent of the data
    """
    purpose: Optional[Purpose] = None
    """
    Purpose of the GIS data (project-specific, analysis, or foundational layers)
    """


class GisData(BaseModel):
    """
    Geospatial data and metadata associated with NEPA projects
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    creator: Optional[str] = None
    """
    Organization or individual.
    """
    description: Optional[str] = None
    """
    Optional description
    """
    extent: Optional[str] = None
    """
    Optional. 
    """
    notes: Optional[str] = None
    """
    Miscellaneous notes.
    """
    container_inventory: Optional[Union[ContainerInventory, ContainerInventory1]] = None
    """
    Inventory of map image container and GIS data container in json format (note inventory should be attached through gis_data_element objects, which may include a list of:
    -	Format: GeoJSON, Shapefile, KML.
    -	Access Method: URL, API, direct upload.
    -	Coordinate System: Spatial reference system.
    -	Bounding Box: Geographic extent.
    -	Purpose: Bespoke, analysis, or base map.
    -	Reference to database: Whether this object references an identified GIS analysis in an official inventory.
    """
    parent_project_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    parent_process_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    parent_document_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    parent_case_event_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    parent_comment_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    parent_engagement_id: Optional[int] = None
    """
    Reference to Foreign object attached to GIS object (one for each other entity table - expected architecture is that there is one foreign key among all these, not all possible relationships filled in)
    """
    created_at: Optional[str] = None
    """
    created date
    """
    centroid_lat: Optional[float] = None
    """
    Option to specify single point or centroid for rapid plotting
    """
    centroid_lon: Optional[float] = None
    """
    Option to specify single point or centroid for rapid plotting
    """
    creator_contact: Optional[Dict[str, Any]] = None
    """
    Contact card-type data for creator.
    """
    map_image: Optional[Dict[str, Any]] = None
    """
    map image data 
    """
    data_container: Optional[Dict[str, Any]] = None
    """
    json container for any attached GIS data
    """
    address: Optional[str] = None
    """
    address of centroid (if applicable)
    """
    last_updated: Optional[str] = None
    """
    Timestamp of last update to this dataset
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class Purpose2(Enum):
    """
    1.	Bespoke GIS Data: Project-specific (boundaries, analysis areas).
    2.	Analysis GIS Data: Data layers used for analysis (e.g., wetlands inventory).
    3.	Base Map Data: Foundational layers (streets, elevation).

    """

    bespoke = 'bespoke'
    analysis = 'analysis'
    base_map = 'base map'


class GisDataElement(BaseModel):
    """
    Individual elements within GIS data containers with specific access and format information
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: Optional[int] = None
    """
    database id
    """
    container_reference: Optional[str] = None
    """
    Reference to header or other information in GIS data container to locate this particular data element
    """
    access_method: Optional[str] = None
    """
    URL, API, direct upload.
    """
    coordinate_system: Optional[str] = None
    """
    Spatial reference system.
    """
    top_left_lat: Optional[float] = None
    """
    Geographic extent.
    """
    top_left_lon: Optional[float] = None
    """
    Geographic extent.
    """
    bot_right_lat: Optional[float] = None
    """
    Geographic extent.
    """
    bot_right_lon: Optional[float] = None
    """
    Geographic extent.
    """
    purpose: Optional[Purpose2] = None
    """
    1.	Bespoke GIS Data: Project-specific (boundaries, analysis areas).
    2.	Analysis GIS Data: Data layers used for analysis (e.g., wetlands inventory).
    3.	Base Map Data: Foundational layers (streets, elevation).

    """
    data_match: Optional[str] = None
    """
    Whether this object references an identified GIS analysis in an official inventory.
    """
    access_info: Optional[Dict[str, Any]] = None
    """
    instructions for access to data
    """
    created_at: Optional[str] = None
    """
    created date
    """
    parent_gis: Optional[int] = None
    """
    Parent GIS data entity (accepts parent_gis or gis_id)
    """
    format: Optional[str] = None
    """
    GeoJSON, Shapefile, KML. (accepts format or data_type)
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class UserRole(BaseModel):
    """
    Defines stakeholders interacting with the NEPA IT system
    """

    id: int
    """
    database id
    """
    name: str
    """
    Title of the role (Agency Staff, Public Commenter).
    """
    description: Optional[str] = None
    """
    Responsibilities and access rights.
    """
    public: Optional[bool] = None
    """
    role is a member of the broader class of public users/stakeholders
    """
    access_policy: Optional[Dict[str, Any]] = None
    """
    access policy json object
    """
    permission_descriptions: Optional[str] = None
    """
    System access levels description
    """
    created_at: Optional[str] = None
    """
    created
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class LegalStructure(BaseModel):
    """
    Legal, policy, or process data guiding the NEPA process, including thresholds and conditions for level of reviews or other decision criteria
    """

    id: int
    """
    database id
    """
    title: str
    """
    Official name.
    """
    citation: str
    """
    Legal reference.
    """
    description: Optional[str] = None
    """
    Summary and relevance.
    """
    issuing_authority: Optional[str] = None
    """
    Government body.
    """
    effective_date: Optional[date] = None
    """
    Implementation date.
    """
    context: Optional[str] = None
    """
    Full text or excerpt.
    """
    compliance_data: Optional[Dict[str, Any]] = None
    """
    Procedural mandates, ideally structured as data using an ontology that includes facts (such as thresholds triggering processes), duties, and actors (e.g., FLINT frames). 
    """
    url: Optional[AnyUrl] = None
    """
    URL of legal reference (e.g. eCFR)
    """
    created_at: Optional[str] = None
    """
    created 
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class DecisionElement(BaseModel):
    """
    Individual criteria or conditions used in NEPA decision-making processes
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    measure: Optional[str] = None
    """
    A description of the type of thing being measured in the criteria (e.g. threshold of contamination)
    """
    intersect: Optional[bool] = None
    """
    If the spatial relationship is a simple intersection (e.g. floodplain)
    """
    spatial_reference: Optional[Dict[str, Any]] = None
    """
     A container for reference to the screening criteria (e.g. api call for wetland data)
    """
    form_text: Optional[str] = None
    """
    Text data to display on a screening form for a user to input data
    """
    form_response_desc: Optional[str] = None
    """
    A description of the type of response expected on the form (e.g. text, select from list, number)
    """
    form_data: Optional[Dict[str, Any]] = None
    """
    Formatted response for a formbuilder application (e.g. likert scale, number, etc)
    """
    evaluation_method: Optional[str] = None
    """
    A description of how the response is matched against the condition and what the results could be. 
    """
    evaluation_dmn: Optional[Dict[str, Any]] = None
    """
    Decision Model Notation description of evaluation of decision element.
    """
    threshold: Optional[float] = None
    """
    numeric value of the triggering measure (if applicable)
    """
    spatial: Optional[bool] = None
    """
    Whether the criterion is a spatial relationship
    """
    category: Optional[str] = None
    """
    The category of the process decision element, such as limitation, condition, core, or extraordinary circumstances.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    last_updated: Optional[AwareDatetime] = None
    """
    This is the last update of the data record in the system.
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    retrieved_timestamp: Optional[AwareDatetime] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """
    expected_evaluation_data: Optional[Dict[str, Any]] = None
    """
    This is a description of the expected data that will be used to evaluate the decision element, such as a list of possible responses or a schema for the data.
    """
    response_data: Optional[Dict[str, Any]] = None
    """
    This jsonb field should contain the structure of data that will be returned by the logic engine - for example, if the response will be a json object containing a series of boolean yes/no indicators, this should specify the schema.
    """
    created_at: Optional[str] = None
    """
    created
    """
    process_model: int
    """
    Parent process model
    """
    legal_structure_id: Optional[int] = None
    """
    If applicable, legal structure related to specific criteria
    """
    title: str
    """
    Name of element
    """
    description: str
    """
    Plain language description of the criterion
    """
    process_model_internal_reference_id: Optional[str] = None
    """
    Process models may have complex decision trees - this string can reference the specific piece of the process model that this decision element applies to. 
    """
    parent_decision_element_id: Optional[int] = None
    """
    If this decision element depends on another decision element (e.g. if answer a is yes, ask question b), this field can be used to reference the parent decision element. 
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """


class ProcessModel(BaseModel):
    """
    Template or framework for NEPA processes
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    database id
    """
    description: str
    """
    Plain language description of the process model 
    """
    bpmn_model: Optional[Dict[str, Any]] = None
    """
    Object containing the BPMN representation of the process
    """
    legal_structure_text: Optional[str] = None
    """
    Reference to legal structure that defines the process (text, cfr reference, etc)
    """
    screening_description: Optional[str] = None
    """
    Plain language description of the screening criteria that would lead to starting the process for an individual project. 
    """
    agency: Optional[str] = None
    """
    Agency responsible for carrying out this process
    """
    DMN_model: Optional[Dict[str, Any]] = None
    """
    Decision model notation (in json wrapper) to structure logic for how to evaluate responses to decision elements. Optionally, each decision element may have individual DMN models.  
    """
    parent_model: Optional[str] = None
    """
    Reference to parent model, if applicable (i.e. if this is a subprocess or flows from a previous process)
    """
    created_at: Optional[str] = None
    """
    created
    """
    title: str
    """
    Name of process model 
    """
    notes: Optional[str] = None
    """
    Miscellaneous notes on process model
    """
    legal_structure_id: Optional[int] = None
    """
    Reference to legal structure entity that defines the process
    """
    screening_desc_json: Optional[Dict[str, Any]] = None
    """
    Plain language description of the screening criteria that would lead to starting the process for an individual project.  (json object option - this should not replace the decision element relationships)
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class ProcessDecisionPayload(BaseModel):
    """
    Data package containing decision-making information
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: int
    """
    Database primary key identifier
    """
    created_at: Optional[str] = None
    """
    created
    """
    process: int
    """
    Reference to the associated process (accepts process field as integer)
    """
    evaluation_data: Optional[Dict[str, Any]] = None
    """
    The actual decision data payload
    """
    data_description: Optional[str] = None
    """
    Description of the payload data
    """
    response: Optional[str] = None
    """
    Response from the decision process
    """
    result: Optional[str] = None
    """
    Result of the decision
    """
    result_bool: Optional[bool] = None
    """
    Boolean result of the decision
    """
    result_notes: Optional[str] = None
    """
    Notes about the decision result
    """
    result_data: Optional[Dict[str, Any]] = None
    """
    Data associated with the result
    """
    result_source: Optional[str] = None
    """
    Source of the decision result
    """
    data_annotation: Optional[str] = None
    """
    Annotations on the payload data
    """
    evaluation_data_annotation: Optional[Dict[str, Any]] = None
    """
    Annotations on the evaluation data
    """
    process_decision_element: Optional[str] = None
    """
    Reference to the decision element this payload responds to
    """
    project: Optional[str] = None
    """
    Reference to the project this decision payload is associated with
    """
    parent_payload: Optional[str] = None
    """
    Reference to parent payload ID (e.g., if this is a response to a submission)
    """
    other: Optional[Dict[str, Any]] = None
    """
    This jsonb field should be used for additional data structures as needed. 
    """
    record_owner_agency: Optional[str] = None
    """
    This is the owner of the original data, generally the authoritative data source.
    """
    data_source_agency: Optional[str] = None
    """
    This is the agency from which this data record was sent or retrieved or in which it is stored, which may be different than the record owner.
    """
    data_source_system: Optional[str] = None
    """
    This is the system from which this data record was sent or retrieved or in which it is stored.
    """
    data_record_version: Optional[str] = None
    """
    This is the version of this data record.
    """
    last_updated: Optional[str] = None
    """
    This is the last update of the data record in the system.
    """
    retrieved_timestamp: Optional[str] = None
    """
    This is the timestamp of a retrieval or transmission (e.g. responding to an API call).
    """


class NepaDataStandard(BaseModel):
    """
    Data standards for the environmental review process conducted under the National Environmental Policy Act (NEPA). This standard provides a framework to ensure that all environmental, social, and economic data collected, used, and submitted during NEPA reviews adhere to consistent definitions, formats, and protocols.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    projects: Optional[List[Project]] = None
    processe_instances: Optional[List[ProcessInstance]] = None
    """
    Collection of NEPA processes
    """
    documents: Optional[List[Document]] = None
    """
    Collection of NEPA documents
    """
    comments: Optional[List[Comment]] = None
    """
    Collection of public comments
    """
    engagements: Optional[List[Engagement]] = None
    """
    Collection of public engagement events
    """
    case_events: Optional[List[CaseEvent]] = None
    """
    Collection of case events
    """
    gis_data: Optional[List[Union[GisData, Dict[str, Any]]]] = None
    """
    Collection of GIS data
    """
    gis_data_elements: Optional[List[GisDataElement]] = None
    """
    Collection of GIS data elements
    """
    user_roles: Optional[List[UserRole]] = None
    """
    Collection of user roles
    """
    decision_elements: Optional[List[DecisionElement]] = None
    """
    Collection of decision elements
    """
    process_models: Optional[List[ProcessModel]] = None
    """
    Collection of process models
    """
    process_decision_payloads: Optional[List[ProcessDecisionPayload]] = None
    """
    Collection of decision payloads
    """
    legal_structures: Optional[List[LegalStructure]] = None
    """
    Collection of legal structures
    """
